{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c01e6b7c-4c68-4529-a609-bc3be3cc79da",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting sqlalchemy==1.3.9\n",
      "  Using cached SQLAlchemy-1.3.9-cp39-cp39-win_amd64.whl\n",
      "Installing collected packages: sqlalchemy\n",
      "  Attempting uninstall: sqlalchemy\n",
      "    Found existing installation: SQLAlchemy 2.0.31\n",
      "    Uninstalling SQLAlchemy-2.0.31:\n",
      "      Successfully uninstalled SQLAlchemy-2.0.31\n",
      "Successfully installed sqlalchemy-1.3.9\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.3.9 which is incompatible.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: ibm_db_sa in c:\\users\\x\\anaconda3\\lib\\site-packages (0.4.0)\n",
      "Requirement already satisfied: sqlalchemy>=0.7.3 in c:\\users\\x\\anaconda3\\lib\\site-packages (from ibm_db_sa) (1.3.9)\n",
      "Requirement already satisfied: ibm-db>=2.0.0 in c:\\users\\x\\anaconda3\\lib\\site-packages (from ibm_db_sa) (3.2.3)\n",
      "Requirement already satisfied: ipython-sql in c:\\users\\x\\anaconda3\\lib\\site-packages (0.5.0)\n",
      "Requirement already satisfied: ipython in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython-sql) (7.31.1)\n",
      "Requirement already satisfied: sqlparse in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython-sql) (0.5.0)\n",
      "Collecting sqlalchemy>=2.0\n",
      "  Using cached SQLAlchemy-2.0.31-cp39-cp39-win_amd64.whl (2.1 MB)\n",
      "Requirement already satisfied: ipython-genutils in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: prettytable in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython-sql) (3.10.0)\n",
      "Requirement already satisfied: six in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython-sql) (1.16.0)\n",
      "Requirement already satisfied: typing-extensions>=4.6.0 in c:\\users\\x\\anaconda3\\lib\\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\x\\anaconda3\\lib\\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.3)\n",
      "Requirement already satisfied: traitlets>=4.2 in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (5.14.3)\n",
      "Requirement already satisfied: setuptools>=18.5 in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (63.4.1)\n",
      "Requirement already satisfied: pygments in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (2.11.2)\n",
      "Requirement already satisfied: pickleshare in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.7.5)\n",
      "Requirement already satisfied: matplotlib-inline in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.1.6)\n",
      "Requirement already satisfied: backcall in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.4.5)\n",
      "Requirement already satisfied: decorator in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.18.1)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\\users\\x\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (3.0.20)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\x\\anaconda3\\lib\\site-packages (from prettytable->ipython-sql) (0.2.5)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\\users\\x\\anaconda3\\lib\\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)\n",
      "Installing collected packages: sqlalchemy\n",
      "  Attempting uninstall: sqlalchemy\n",
      "    Found existing installation: SQLAlchemy 1.3.9\n",
      "    Uninstalling SQLAlchemy-1.3.9:\n",
      "      Successfully uninstalled SQLAlchemy-1.3.9\n",
      "Successfully installed sqlalchemy-2.0.31\n"
     ]
    }
   ],
   "source": [
    "!pip install sqlalchemy==1.3.9\n",
    "!pip install ibm_db_sa\n",
    "!pip install ipython-sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "7a758035-c06a-4306-8120-8697e727eb20",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Connect to the database"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "44b7db26-435b-4305-8176-c14f88c55f05",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The sql extension is already loaded. To reload it, use:\n",
      "  %reload_ext sql\n"
     ]
    }
   ],
   "source": [
    "%load_ext sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "ea539d94-8385-4108-a6d4-5bb6fa949819",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 281, in warned\n",
      "    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 599, in create_engine\n",
      "    dbapi = dbapi_meth(**dbapi_args)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\ibm_db_sa\\ibm_db.py\", line 130, in import_dbapi\n",
      "    import ibm_db_dbi as module\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\ibm_db_dbi.py\", line 45, in <module>\n",
      "    import ibm_db\n",
      "ImportError: DLL load failed while importing ibm_db: Belirtilen modül bulunamadı.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 281, in warned\n",
      "    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 599, in create_engine\n",
      "    dbapi = dbapi_meth(**dbapi_args)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\ibm_db_sa\\ibm_db.py\", line 130, in import_dbapi\n",
      "    import ibm_db_dbi as module\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\ibm_db_dbi.py\", line 45, in <module>\n",
      "    import ibm_db\n",
      "ImportError: DLL load failed while importing ibm_db: Belirtilen modül bulunamadı.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%sql ibm_db_sa://sdk38546:cwn1%40l380qx5qb3k@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "92cbd1e9-815a-4f9f-8766-87bcaf31e934",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 82, in set\n",
      "    raise ConnectionError(\n",
      "sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%sql select distinct(LAUNCH_SITE) from SPACEXTBL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "854dc8c0-af03-4b93-a2e4-4782f486bc44",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 281, in warned\n",
      "    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 546, in create_engine\n",
      "    u = _url.make_url(url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 842, in make_url\n",
      "    return _parse_url(name_or_url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 903, in _parse_url\n",
      "    components[\"port\"] = int(components[\"port\"])\n",
      "ValueError: invalid literal for int() with base 10: 'my-port'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 281, in warned\n",
      "    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 546, in create_engine\n",
      "    u = _url.make_url(url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 842, in make_url\n",
      "    return _parse_url(name_or_url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 903, in _parse_url\n",
      "    components[\"port\"] = int(components[\"port\"])\n",
      "ValueError: invalid literal for int() with base 10: 'my-port'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1cbb9d57-8128-40ff-a1da-4a70eb0d99bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 281, in warned\n",
      "    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 546, in create_engine\n",
      "    u = _url.make_url(url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 842, in make_url\n",
      "    return _parse_url(name_or_url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 903, in _parse_url\n",
      "    components[\"port\"] = int(components[\"port\"])\n",
      "ValueError: invalid literal for int() with base 10: 'my-port'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 281, in warned\n",
      "    return fn(*args, **kwargs)  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 546, in create_engine\n",
      "    u = _url.make_url(url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 842, in make_url\n",
      "    return _parse_url(name_or_url)\n",
      "  File \"C:\\Users\\x\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 903, in _parse_url\n",
      "    components[\"port\"] = int(components[\"port\"])\n",
      "ValueError: invalid literal for int() with base 10: 'my-port'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6f02ac56-dbd0-4ddb-b9bd-bf10b101afba",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d7ad8ea-af4e-484f-859e-ad8cca3b5866",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
